import { Prisma } from "@prisma/client";
import { digestCanonicalJson } from "@airoaming/shared";
import { readFile } from "node:fs/promises";
import * as path from "node:path";
import { MigrationAuditError, readVerifiedSnapshot, type VerifiedSnapshot } from "./migration-audit.service.js";
import { normalizeMigrationDecisionArtifact, type MigrationDecisionArtifact } from "./migration-decision.js";
import { MigrationLedgerError, type MigrationRunRecord } from "./migration-ledger.js";
import { mapLegacyComicFormat } from "./comic-format-migration.plugin.js";
import { createComicFormatReport, type ComicFormatReport, type ComicFormatReportProject } from "./migration-report.js";
import { PrismaMigrationLedgerRepository } from "./prisma-migration-ledger.repository.js";
import { PrismaService } from "../persistence/prisma.service.js";

export class CharacterShadowImportError extends Error { constructor(readonly code: string) { super(code); } }
interface CharacterPlan { targetId: string; sourceKey: string; sourceStorageKey: string; sourceDigest: `sha256:${string}`; payloadDigest: `sha256:${string}`; projectId: string; name: string; normalizedName: string; role: string; level: string; entityType: string; status: string; appearance: string; personality: string; promptFragment: string; source: string; createdAt: Date; updatedAt: Date; finalizedAt: Date | null; }
function object(value: unknown, code: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new CharacterShadowImportError(code); return value as Record<string, unknown>; }
function field(value: Record<string, unknown>, key: string, fallback = ""): string { return typeof value[key] === "string" && value[key].trim() ? value[key] as string : fallback; }
function dateField(value: Record<string, unknown>, key: string, fallback = "2000-01-01T00:00:00.000Z"): Date { const parsed = new Date(field(value, key, fallback)); return Number.isNaN(parsed.getTime()) ? new Date(fallback) : parsed; }
function projectSourceKey(projectId: string): string { return `workspace-v1:${projectId}:Project:${projectId}`; }
function characterSourceKey(projectId: string, legacyId: string): string { return `workspace-v1:${projectId}:Character:${legacyId}`; }
async function payload(snapshot: VerifiedSnapshot, key: string): Promise<{ item: { sha256: `sha256:${string}` }; value: Record<string, unknown> }> { const { item, bytes } = await snapshot.readPayload(key); try { return { item, value: object(JSON.parse(bytes.toString("utf8")), "MIGRATION_SOURCE_JSON_INVALID") }; } catch (error) { if (error instanceof CharacterShadowImportError) throw error; throw new CharacterShadowImportError("MIGRATION_SOURCE_JSON_INVALID"); } }

/** G3-M3-A7：导入 shared/characters.json 的正式 Character 身份；视觉/Asset 留给后续切片。 */
export class CharacterShadowImporter {
  private readonly ledger: PrismaMigrationLedgerRepository;
  constructor(private readonly prisma: PrismaService, ledger?: PrismaMigrationLedgerRepository) { this.ledger = ledger ?? new PrismaMigrationLedgerRepository(prisma); }
  async import(snapshotPath: string, decisionsPath: string, options: { runId?: string; startedAt?: string } = {}): Promise<{ run: MigrationRunRecord; report: ComicFormatReport; decisions: MigrationDecisionArtifact }> {
    const snapshot = await readVerifiedSnapshot(snapshotPath); const decisions = await this.readDecisions(decisionsPath, snapshot.sealed.sourceManifestDigest);
    const run = await this.ledger.beginRun({ kind: "shadow", importerVersion: "g3-m3-a7", sourceManifestDigest: snapshot.sourceManifest.manifestDigest, snapshotManifestDigest: snapshot.snapshotManifest.manifestDigest, decisionsDigest: decisions.decisionsDigest, id: options.runId, startedAt: options.startedAt });
    try {
      const projects: ComicFormatReportProject[] = []; let characterCount = 0; let warningCount = 0;
      const projectItems = snapshot.sourceManifest.items.filter((item) => /^projects\/[^/]+\/project\.json$/.test(item.storageKey)).sort((a, b) => a.storageKey.localeCompare(b.storageKey));
      for (const projectItem of projectItems) {
        const legacyProjectId = projectItem.storageKey.split("/")[1]; const metadata = (await payload(snapshot, projectItem.storageKey)).value; const mapping = mapLegacyComicFormat(metadata.comicFormat); const decision = decisions.entries.find((entry) => entry.sourceKey === projectSourceKey(legacyProjectId)); const targetProjectId = PrismaMigrationLedgerRepository.stableEntityId("Project", projectSourceKey(legacyProjectId)); const targetProject = await this.prisma.database().project.findUnique({ where: { id: targetProjectId } });
        const characterItem = snapshot.sourceManifest.items.find((item) => item.storageKey === `projects/${legacyProjectId}/shared/characters.json`); const plans = targetProject && characterItem ? await this.buildPlans(snapshot, characterItem.storageKey, legacyProjectId, targetProjectId) : [];
        if (!targetProject || (characterItem === undefined && plans.length === 0)) warningCount += targetProject ? 0 : 1;
        if (targetProject) await this.ledger.withTransaction(async (tx) => { for (const plan of plans) { await this.importPlan(tx, run.id, plan); characterCount += 1; } });
        const blocked = !targetProject; const issueKey = blocked ? `project:${legacyProjectId}:character-target` : null; projects.push({ projectId: legacyProjectId, sourceStorageKey: projectItem.storageKey, sourceDigest: projectItem.sha256, originalComicFormat: { kind: mapping.originalValueKind, preview: mapping.originalValuePreview }, mappingKind: mapping.mappingKind, targetComicFormat: mapping.targetComicFormat ?? decision?.chosenComicFormat ?? null, layoutPresetIntent: mapping.layoutPresetIntent, issueKey, resolutionStatus: issueKey ? "open" : "not_needed", importStatus: blocked ? "blocked" : "imported" });
        if (blocked) await this.ledger.withTransaction((tx) => this.ledger.recordGenericIssueInTransaction(tx, run.id, { issueKey: issueKey!, code: "MIGRATION_TARGET_NOT_FOUND", entityType: "Project", entityId: targetProjectId, sourceKey: projectSourceKey(legacyProjectId), storageKey: projectItem.storageKey, detailJson: { schemaVersion: 1, projectId: legacyProjectId, reason: "Project/Chapter shadow must run first" } }));
      }
      const report = createComicFormatReport(projects, { warningCount, entityCounts: { Character: characterCount } }); const finished = await this.ledger.finishRun(run.id, { status: report.summary.unresolvedBlockerCount > 0 ? "blocked" : "succeeded", reportDigest: report.reportDigest, counts: { ...report.summary, characterCount }, verification: { schemaVersion: 1, sourceManifestVerified: true, snapshotManifestVerified: true, characterShadowImported: true }, finishedAt: new Date().toISOString() }); return { run: finished, report, decisions };
    } catch (error) { const code = error instanceof Error && "code" in error ? String((error as Error & { code: unknown }).code) : "MIGRATION_IMPORT_FAILED"; try { await this.ledger.finishRun(run.id, { status: "failed", errorCode: code, finishedAt: new Date().toISOString() }); } catch { /* preserve original failure */ } if (error instanceof CharacterShadowImportError || error instanceof MigrationLedgerError || error instanceof MigrationAuditError) throw error; throw new CharacterShadowImportError(code); }
  }
  private async readDecisions(decisionsPath: string, expected: `sha256:${string}`): Promise<MigrationDecisionArtifact> { if (!path.isAbsolute(decisionsPath)) throw new CharacterShadowImportError("MIGRATION_DECISION_PATH_INVALID"); try { return normalizeMigrationDecisionArtifact(JSON.parse(await readFile(decisionsPath, "utf8")) as unknown, expected); } catch (error) { if (error instanceof Error && "code" in error) throw new CharacterShadowImportError(String((error as Error & { code: unknown }).code)); throw new CharacterShadowImportError("MIGRATION_DECISION_INVALID"); } }
  private async buildPlans(snapshot: VerifiedSnapshot, storageKey: string, legacyProjectId: string, targetProjectId: string): Promise<CharacterPlan[]> { const { item, value } = await payload(snapshot, storageKey); const input = Array.isArray(value.characters) ? value.characters : []; return input.filter((entry): entry is Record<string, unknown> => Boolean(entry && typeof entry === "object" && !Array.isArray(entry))).map((entry, index) => { const legacyId = field(entry, "id", `char_${String(index + 1).padStart(3, "0")}`); const name = field(entry, "name", `角色 ${index + 1}`).trim().slice(0, 60); if (!name) throw new CharacterShadowImportError("MIGRATION_CHARACTER_NAME_INVALID"); const sourceKey = characterSourceKey(legacyProjectId, legacyId); const targetId = PrismaMigrationLedgerRepository.stableEntityId("Character", sourceKey); const createdAt = dateField(entry, "createdAt"); const updatedAt = dateField(entry, "updatedAt", createdAt.toISOString()); const finalizedAt = typeof entry.finalizedAt === "string" ? dateField(entry, "finalizedAt") : null; const normalizedName = name.toLowerCase(); const plan = { targetId, sourceKey, sourceStorageKey: storageKey, sourceDigest: item.sha256, projectId: targetProjectId, name, normalizedName, role: field(entry, "role"), level: field(entry, "level", index === 0 ? "lead" : "recurring"), entityType: field(entry, "entityType", "human"), status: field(entry, "status", "draft"), appearance: field(entry, "appearance"), personality: field(entry, "personality"), promptFragment: field(entry, "promptFragment"), source: field(entry, "source", "script_outline"), createdAt, updatedAt, finalizedAt }; const payload = { ...plan, createdAt: createdAt.toISOString(), updatedAt: updatedAt.toISOString(), finalizedAt: finalizedAt?.toISOString() ?? null }; return { ...plan, payloadDigest: digestCanonicalJson(payload) }; }); }
  private async importPlan(tx: Prisma.TransactionClient, runId: string, plan: CharacterPlan): Promise<void> { const existingSource = await tx.importedEntitySource.findUnique({ where: { sourceKey: plan.sourceKey } }); if (existingSource && (existingSource.entityId !== plan.targetId || existingSource.sourceDigest !== plan.sourceDigest || existingSource.payloadDigest !== plan.payloadDigest)) throw new MigrationLedgerError("MIGRATION_SOURCE_CONFLICT"); const existing = await tx.character.findUnique({ where: { id: plan.targetId } }); if (existing && (existing.projectId !== plan.projectId || existing.normalizedName !== plan.normalizedName || existing.name !== plan.name)) throw new MigrationLedgerError("MIGRATION_PAYLOAD_CONFLICT"); if (!existing) await tx.character.create({ data: { id: plan.targetId, projectId: plan.projectId, name: plan.name, normalizedName: plan.normalizedName, role: plan.role, level: plan.level, entityType: plan.entityType, status: plan.status, appearance: plan.appearance, personality: plan.personality, promptFragment: plan.promptFragment, source: plan.source, rowVersion: 0, createdAt: plan.createdAt, updatedAt: plan.updatedAt, finalizedAt: plan.finalizedAt } }); await this.ledger.recordImportedEntitySourceInTransaction(tx, runId, { sourceKey: plan.sourceKey, entityType: "Character", entityId: plan.targetId, sourceStorageKey: plan.sourceStorageKey, sourceDigest: plan.sourceDigest, payloadDigest: plan.payloadDigest, provenanceStatus: "partial" }); }
}
